= Untyped Arithmetic Expressions

== 3.2.4

#let s2total = 3 + 9 + 27

$S_0$ has 0 elements. $S_1$ has 3 elements. $S_2$ has 3 for the constants, 9 for the first union, and 27 for the third
for a total of 39. $S_3$ has 3 for the constants, 117 for the first union and 59319 for the second union, for a total of
size of 59439.

== 3.2.5

We induct on $i$. For the base case $i = 0$, it is trivial that $nothing subset.eq S_1$.

Say that we have shown $S_(n - 1) subset.eq S_n$. We know that the constants must be elements of $S_(n+1)$, and every
other element of $S_n$ must be generated by one of the two unions using elements from $S_(n-1)$. However, the inductive
hypothesis and the definition of $S_(n+1)$ imply that $S_(n+1)$ contains at least the elements generated using elements
from $S_(n-1)$ in the form of the two unions as well, allowing us to conclude that $S_n subset.eq S_(n+1)$ as desired.
